### ISSUE TITLE
Vagrant fails to install pe 386

### ISSUE THREAD

**Issue by benh57** [natemccurdy/puppet-upgrade-workplace#1]
I'm guessing this is an oscar issue?

 vagrant up pe-386-master

....

==> pe-386-master: Running provisioner: pe_bootstrap...
Cannot fetch installer puppet-enterprise-3.8.6-el-7-x86_64.tar.gz; no download source available.

Installers available for use:
The Puppet Enterprise installer puppet-enterprise-3.8.6-el-7-x86_64.tar.gz
is not available. Please set the `download_root` config option to a valid
mirror, or add the installer yourself by using the `vagrant pe-build copy`
command. Downloads for Puppet Enterprise are available for download at
https://puppetlabs.com/puppet/puppet-enterprise/

**Comment by benh57** [comment]
Here's the fix.

https://github.com/oscar-stack/oscar/issues/16

Suggest adding that config/pe_build.yaml file to this repo.

**Comment by natemccurdy** [comment]
Thanks for reporting this @benh57 

I've pushed a commit (b0d3a914f105691a5850d5f0edc6445284534d99) that adds a pe_build.yaml so that the Vagrant plugin can automatically download the PE installers.
